In [ ]:
!pip3 install torch
!pip3 install torchvision

# **2D with Numpy**

In [ ]:
import numpy as np

# 2차원 행렬
t = np.array([[1., 2., 3.],[4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [ ]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  2
Shape of t:  (4, 3)


# **Pytorch Tensor** (2D)

In [ ]:
import torch

t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                       ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
print(t.dim()) # rank(차원)
print(t.shape)
print(t.size()) # == shape(크기)

2
torch.Size([4, 3])
torch.Size([4, 3])


In [7]:
# 첫번째 차원 전체 선택 -> 두번째 차원에서 맨 마지막 제외하고 다 선택
print(t[:, :-1])

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


# **Broadcasting**

In [8]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [9]:
# Vector + scalar

m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)

tensor([[4., 5.]])


In [10]:
# 1x2 Vector + 2x1 Vector

m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


In [ ]:
# 브로드캐스팅 과정에서 실제로 두 텐서가 어떻게 변경되는지 보겠습니다.
[1, 2]
==> [[1, 2],
     [1, 2]]
[3]
[4]
==> [[3, 3],
     [4, 4]]


# **Matrix Multiplication VS Multiplication**

In [11]:
# Matrix multiplication - 행렬 곱셈 .matmul()

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # "2" x 2
print('Shape of Matrix 2: ', m2.shape) #  2  x "1"
print(m1.matmul(m2)) # "2" x "1"

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [ ]:
# Multiplication -