<a href="https://colab.research.google.com/github/GodHyeonG/PyTorch/blob/main/02_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import torch

t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [3]:
# 3차원 텐서

print(ft.shape)

torch.Size([2, 2, 3])


# **뷰(View)** - 원소의 수 유지하면서 텐서의 크기 변경

1) 3차원 텐서에서 2차원 텐서로 변경

In [3]:
print(ft.view([-1, 3])) # ft 텐서를 (?, 3) 크기로 변경
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


2) 3차원 텐서의 크기 변경

In [4]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


# **스퀴즈(Squeeze)** - 1인 차원을 제거

In [5]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [6]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


# **언스퀴즈(Unsqueeze)** - 특정 위치에 1인 차원을 추가

In [7]:
ft = torch.FloatTensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [9]:
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0 : 첫번째 차원
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [10]:
# view로도 구현 가능 - 2차원으로 바꾸고 싶으면서 첫번째 차원은 1이길 원함

print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [11]:
# 인덱스 1 : 두번째 차원 - (3,) 벡터 -> (3, 1) 텐서
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [12]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


# **연결하기(concatenate)**

In [13]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [14]:
# torch.cat : 어느 차원 늘릴지 인자로 줄 수 있음 - dim=0 : 첫번째 차원 늘림
print(torch.cat([x, y], dim=0)) # (2 x 2) -> (4 x 2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [15]:
print(torch.cat([x, y], dim=1)) # (2 x 2) -> (2 x 4)

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


# **스택킹(Stacking)**

In [16]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [17]:
print(torch.stack([x, y, z])) # (3 x 2) 텐서

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [18]:
# 동일한 작업

print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [19]:
# dim=1 인자 - 두번째 차원이 증가하도록 쌓음

print(torch.stack([x, y, z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])
