<a href="https://colab.research.google.com/github/GodHyeonG/PyTorch/blob/main/02_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip3 install torch
!pip3 install torchvision

# **2D with Numpy**

In [ ]:
import numpy as np

# 2차원 행렬
t = np.array([[1., 2., 3.],[4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [ ]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  2
Shape of t:  (4, 3)


# **Pytorch Tensor** (2D)

In [ ]:
import torch

t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                       ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
print(t.dim()) # rank(차원)
print(t.shape)
print(t.size()) # == shape(크기)

2
torch.Size([4, 3])
torch.Size([4, 3])


In [ ]:
# 첫번째 차원 전체 선택 -> 두번째 차원에서 맨 마지막 제외하고 다 선택
print(t[:, :-1])

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


# **Broadcasting**

In [ ]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [ ]:
# Vector + scalar

m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)

tensor([[4., 5.]])


In [ ]:
# 1x2 Vector + 2x1 Vector

m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


In [ ]:
# 브로드캐스팅 과정에서 실제로 두 텐서가 어떻게 변경되는지 보겠습니다.
[1, 2]
==> [[1, 2],
     [1, 2]]
[3]
[4]
==> [[3, 3],
     [4, 4]]


# **Matrix Multiplication VS Multiplication**

In [ ]:
# Matrix multiplication - 행렬 곱셈 .matmul()

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # "2" x 2
print('Shape of Matrix 2: ', m2.shape) #  2  x "1"
print(m1.matmul(m2)) # "2" x "1"

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [ ]:
# Multiplication, element-wise * 또는 .mul()

import torch

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2 (m2의 크기 변환됨)
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


# **평균(Mean)**

In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t.mean())

tensor(2.5000)


In [ ]:
# dim=0, 즉 '행' 제거
print(t.mean(dim=0))

tensor([2., 3.])


dim=0 : 첫번째 차원 (행)

인자로 dim을 주면, 해당 차원을 제거한다는 의미(행렬에서 '열'만 남김)

기존 행렬크기 (2, 2)에서 열의 차원만 보존되며 (1, 2)

In [ ]:
# dim=1, 즉 '열' 제거

print(t.mean(dim=1))

tensor([1.5000, 3.5000])


In [ ]:
# dim=-1, 즉 마지막 차원(열) 제거

print(t.mean(dim=-1))

tensor([1.5000, 3.5000])


# **최대(Max)와 아그맥스(ArgMax)**

In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t.max())

tensor(4.)


In [ ]:
# Return two values: max and argmax

print(t.max(dim=0))

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [ ]:
# [1, 1]가 무슨 의미인지 봅시다. 기존 행렬을 다시 상기해봅시다.
[[1, 2],
 [3, 4]]
첫번째 열에서 0번 인덱스는 1, 1번 인덱스는 3입니다.
두번째 열에서 0번 인덱스는 2, 1번 인덱스는 4입니다.
다시 말해 3과 4의 인덱스는 [1, 1]입니다.

In [ ]:
print('Max: ', t.max(dim=0)[0]) # max 값만 return
print('Argmax: ', t.max(dim=0)[1]) # argmax 값만 return

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])
